# Site settings
title: Dispute Hero
email: jeff@m2bllc.com
description: "We make credit stuff awesome!"
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll
highlighter: false

# Build settings
markdown: kramdown
permalink: pretty
